import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/ui/navbar";
import ParticlesBackground from "@/components/ui/Background";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <head>
        <style>
          {`@import url(&apos;https://fonts.googleapis.com/css2?family=Baloo+2&family=Russo+One&display=swap&apos;);`}
        </style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen bg-cover bg-center bg-fixed`}
      >
        <ParticlesBackground />
        <Navbar />
        <main className="min-h-screen">{children}</main>
      </body>
    </html>
  );
}
